### ISSUE TITLE
"Current Position", "Price when ordered" and "ordered at columns" not showing values

### ISSUE THREAD

**Issue by Dolivent** [pareeohnos/ktrade#15]
![image](https://user-images.githubusercontent.com/89076425/133445559-8249c511-35b4-4918-9a51-bc8af1654d24.png)
I have 3 AAPL trades with the option to trim all of them. one would sell 2 shares, another would sell 20

**Comment by Dolivent** [comment]
The potential solution might be to make the log a log, and not have any sell actions. Then have a separate positions panel in the dashboard with the sell actions

**Comment by pareeohnos** [comment]
So do you think in a situation like this, it should just combine all trades for a single ticker into a single position, rather than keeping them as separated trades? If so, how do you see it working in the situation where

- Buy 100 AAPL
- Sell 1/3
- Buy another 50 AAPL

If I then trim 1/3, what does the app deem the original position to calculate the 1/3 position?

**Comment by Dolivent** [comment]
I think youre right. Keeping them like this is the right methodology. Would just need to show the original position and the shares remaining. Or a column titled  "% of position remaining"

**Comment by Dolivent** [comment]
Sorry, the title is unclear. This is a combination of 2 issues. 
1. Suggestion of combining all orders for the same stock into one row, which we agreed is not right. No change required other than making the columns show the values titled
2. The sell positions not being consistent % of the original position. I have created a separate 'issue' for the sell proportions

**Comment by Dolivent** [comment]
![image](https://user-images.githubusercontent.com/89076425/133479198-4a75bb58-2ece-40c3-a758-51571efa3cb0.png)
 Filled not showing the actual filled amount
